package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import controller.ControllerCliente;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;

public class FrameCreaOrdine extends JFrame {
    private JPanel pannelloPrincipale;
    private JPanel pannelloForm;
    private JPanel pannelloBottoni;
    private JButton xButton;
    private JTextField indirizzoSpedizione;
    private JLabel LabelIndirizzo;
    private JLabel LabelNumeroCarta;
    private JTextField numCartaTextField;
    private JLabel LabelCCV;
    private JTextField CCVTextField;
    private JLabel LabelMese;
    private JTextField meseTextField;
    private JLabel LabelAnno;
    private JTextField annoTextField;
    private JButton bottoneConferma;
    private JLabel Esito;

    private String emailUtente;
    private FrameCarrello frameCarrello;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pannelloPrincipale = new JPanel();
        pannelloPrincipale.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        pannelloForm = new JPanel();
        pannelloForm.setLayout(new GridLayoutManager(10, 1, new Insets(0, 0, 0, 0), -1, -1));
        pannelloPrincipale.add(pannelloForm, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        LabelIndirizzo = new JLabel();
        LabelIndirizzo.setText("Indirizzo di Spedizione: ");
        pannelloForm.add(LabelIndirizzo, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        indirizzoSpedizione = new JTextField();
        indirizzoSpedizione.setText("");
        pannelloForm.add(indirizzoSpedizione, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        LabelNumeroCarta = new JLabel();
        LabelNumeroCarta.setText("Numero Carta di credito o di debito [American Express non supportata]:");
        pannelloForm.add(LabelNumeroCarta, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        numCartaTextField = new JTextField();
        pannelloForm.add(numCartaTextField, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        LabelCCV = new JLabel();
        LabelCCV.setText("CCV:");
        pannelloForm.add(LabelCCV, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        CCVTextField = new JTextField();
        pannelloForm.add(CCVTextField, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        LabelMese = new JLabel();
        LabelMese.setText("Mese di scadenza della carta [MM]:");
        pannelloForm.add(LabelMese, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        meseTextField = new JTextField();
        pannelloForm.add(meseTextField, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        LabelAnno = new JLabel();
        LabelAnno.setText("Anno di scadenza della carta [YYYY]:");
        pannelloForm.add(LabelAnno, new GridConstraints(8, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        annoTextField = new JTextField();
        pannelloForm.add(annoTextField, new GridConstraints(9, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        pannelloBottoni = new JPanel();
        pannelloBottoni.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        pannelloPrincipale.add(pannelloBottoni, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        bottoneConferma = new JButton();
        bottoneConferma.setText("Conferma Ordine");
        pannelloBottoni.add(bottoneConferma, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        xButton = new JButton();
        xButton.setText("Esci");
        pannelloBottoni.add(xButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Esito = new JLabel();
        Esito.setText("");
        pannelloPrincipale.add(Esito, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pannelloPrincipale;
    }

    public FrameCreaOrdine(String emailUtente, FrameCarrello frameCarrello) {
        this.emailUtente = emailUtente;
        this.frameCarrello = frameCarrello;

        setTitle("Creazione ordine");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Consigliato DISPOSE per chiudere solo questa finestra
        setLocationRelativeTo(null);
        setContentPane(pannelloPrincipale);

        impostaEventi();

        this.setVisible(true);
    }

    private void impostaEventi() {
        // Evento per il bottone Chiudi
        xButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Chiude la finestra
                dispose();
            }
        });

        // Evento per il bottone Conferma
        bottoneConferma.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Esito.setText("in attesa di una risposta dal server...");
                elaboraDati();
                frameCarrello.aggiornaCarrello();
            }
        });

        indirizzoSpedizione.setText(new ControllerCliente(emailUtente).getIndirizzoDefaultCliente(emailUtente));
    }

    private void elaboraDati() {
        ControllerCliente controllerCliente = new ControllerCliente(emailUtente);

        try {
            String ccv_text = CCVTextField.getText();
            String indirizzo = indirizzoSpedizione.getText();
            if (ccv_text.length() != 3) {
                JOptionPane.showMessageDialog(this,
                        "Il CCV deve essere di 3 cifre.",
                        "Errore di formato dei dati",
                        JOptionPane.ERROR_MESSAGE);
                throw new IllegalArgumentException();
            }
            if (numCartaTextField.getText().length() != 16) {
                JOptionPane.showMessageDialog(this,
                        "Il numero della carta deve essere di 16 cifre.",
                        "Errore di formato dei dati",
                        JOptionPane.ERROR_MESSAGE);
                throw new IllegalArgumentException();
            }
            if (indirizzo.length() < 5 || indirizzo.length() > 100 || !indirizzo.matches("^[\\p{L}\\p{N} ]+$")) {
                JOptionPane.showMessageDialog(this,
                        "L'indirizzo deve essere composto da lettere e numeri, e deve essere compreso tra 5 e 100 caratteri.",
                        "Errore di formato dei dati",
                        JOptionPane.ERROR_MESSAGE);
                throw new IllegalArgumentException();
            }


            int ccv = Integer.parseInt(ccv_text);
            int mese = Integer.parseInt(meseTextField.getText());
            int anno = Integer.parseInt(annoTextField.getText());
            long numCarta = Long.parseLong(numCartaTextField.getText());
            if (mese < 1 || mese > 12 || anno < LocalDate.now().getYear() || anno > 2100) {
                JOptionPane.showMessageDialog(this,
                        "Mese o anno non validi. Assicurati di aver inserito i dati correttamente.",
                        "Errore di formato dei dati",
                        JOptionPane.ERROR_MESSAGE);
                throw new IllegalArgumentException();
            }


            boolean check = controllerCliente.creaOrdine(indirizzoSpedizione.getText(), numCarta, ccv, mese, anno);

            if (check) {
                JOptionPane.showMessageDialog(null, "Ordine creato con successo!");
                Esito.setText("Ordine creato");
                dispose();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Errore durante la creazione dell'ordine.", "Ordine vuoto o pagamento non andato a buon fine",
                        JOptionPane.ERROR_MESSAGE);
                Esito.setText("Ordine non creato");
            }
        } catch (NumberFormatException ex) {
            // Se l'utente inserisce lettere nei campi degli interi, catturiamo l'errore
            JOptionPane.showMessageDialog(this,
                    "Assicurati di aver inserito correttamente i dati.",
                    "Errore di formato dei dati",
                    JOptionPane.ERROR_MESSAGE);
            Esito.setText("Ordine non creato");

        } catch (IllegalArgumentException e) {
            Esito.setText("Ordine non creato");
        }/*catch (Exception e){
            JOptionPane.showMessageDialog(this, "Errore sconosciuto, riprovare più tardi", "Errore Server", JOptionPane.ERROR_MESSAGE);
        }*/
    }

/* check funzionamento
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new FrameCreaOrdine("r.giove@gmail.com"));
    }

 */
}
