package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import controller.ControllerAmministratore;
import controller.ControllerCliente;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.function.Consumer;

public class FrameRicercaProdotti extends JFrame {
    //variabili per il GUI Designer
    private JPanel MainPane;
    private JButton btnCerca;
    private JComboBox<String> cmbCategoriaRicerca;
    private JTextField txtElementoDaCercare;

    //variabili per la logica BCED
    private ControllerCliente controllerCliente;
    private ControllerAmministratore controllerAmministratore;
    private boolean isAdmin; //sarà il nostro modo per riconoscere
    // se questa frame è stata aperta da FrameCliente o da FrameAmministratore

    private Consumer<List<String[]>> onRisultatiTrovati;

    //costruttore
    public FrameRicercaProdotti(ControllerCliente controller, Consumer<List<String[]>> callbackRisultati) {
        this.controllerCliente = controller;
        this.onRisultatiTrovati = callbackRisultati;
        this.isAdmin = false;
        setupListener();
    }

    public FrameRicercaProdotti(ControllerAmministratore controller, Consumer<List<String[]>> callbackRisultati) {
        this.controllerAmministratore = controller;
        this.onRisultatiTrovati = callbackRisultati;
        this.isAdmin = true;
        setupListener();
    }

    private void setupListener() {
        btnCerca.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Previene errori se non c'è nulla selezionato
                String categoria = "";
                if (cmbCategoriaRicerca.getSelectedItem() != null) {
                    categoria = cmbCategoriaRicerca.getSelectedItem().toString();
                }

                String parolaChiave = txtElementoDaCercare.getText();

                List<String[]> righe;
                if (isAdmin) {
                    righe = ControllerAmministratore.ricercaProdottoInCatalogo(categoria, parolaChiave);
                } else {
                    righe = ControllerCliente.ricercaProdottoInCatalogo(categoria, parolaChiave);
                }
                onRisultatiTrovati.accept(righe);
                JFrame frameAttuale = (JFrame) SwingUtilities.getWindowAncestor(MainPane);
                if (frameAttuale != null) {
                    frameAttuale.dispose();
                }
            }
        });
    }

    //metodi
    public static JFrame apri_form_ricerca_cliente(ControllerCliente controller, Consumer<List<String[]>> callbackRisultati) {
        JFrame frame = new JFrame("Ricerca Prodotti");
        FrameRicercaProdotti form = new FrameRicercaProdotti(controller, callbackRisultati);

        frame.setContentPane(form.MainPane);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setSize(500, 300);
        frame.setResizable(false);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        return frame;
    }

    public static JFrame apri_form_ricerca_admin(ControllerAmministratore controller, Consumer<List<String[]>> callbackRisultati) {
        JFrame frame = new JFrame("Ricerca Prodotti");
        FrameRicercaProdotti form = new FrameRicercaProdotti(controller, callbackRisultati);

        frame.setContentPane(form.MainPane);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setSize(500, 300);
        frame.setResizable(false);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        return frame;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPane = new JPanel();
        MainPane.setLayout(new GridLayoutManager(3, 3, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Parola Chiave:");
        MainPane.add(label1, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Cerca per:");
        MainPane.add(label2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnCerca = new JButton();
        btnCerca.setText("Cerca");
        MainPane.add(btnCerca, new GridConstraints(2, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtElementoDaCercare = new JTextField();
        txtElementoDaCercare.setText("");
        MainPane.add(txtElementoDaCercare, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        cmbCategoriaRicerca = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("nome");
        defaultComboBoxModel1.addElement("categoria");
        defaultComboBoxModel1.addElement("descrizione");
        cmbCategoriaRicerca.setModel(defaultComboBoxModel1);
        MainPane.add(cmbCategoriaRicerca, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPane;
    }

}
