package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import controller.ControllerCliente;
import entity.Ordine;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;

//TODO: verificarne la funzionalità
public class FrameStoricoOrdini extends JFrame {
    //variabili per il GUI Designer
    private JPanel StoricoOrdiniPane;
    private JScrollPane MainPanel;
    private JTable tabellaOrdini;

    //variabili per la logica BCED
    private ControllerCliente controller;
    private List<Ordine> listaOrdiniAttuali;

    //costruttore della boundary
    public FrameStoricoOrdini(ControllerCliente controller){
        this.controller = controller;

        setTitle("Storico Ordini");
        setContentPane(StoricoOrdiniPane);
        setSize(600, 400);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);

        fillTabella();
        addListenerTabella(); //il listener per poter interagire con la tabella
    }

    private void fillTabella() {
   //metodo di test
        System.out.println("PROVA");
    }
    private void addListenerTabella(){
        tabellaOrdini.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked (MouseEvent e){
                if (e.getClickCount() == 2){
                    int rigaSelezionata = tabellaOrdini.getSelectedRow();

                    if (rigaSelezionata != -1){
                        Ordine ordineSelezionato = listaOrdiniAttuali.get(rigaSelezionata);
                        mostraDettagliOrdine(ordineSelezionato);
                    }
                }
            }
        });
    }

    private void mostraDettagliOrdine(Ordine ordineSelezionato){
        setTitle("Aspetto per farlo");
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        StoricoOrdiniPane = new JPanel();
        StoricoOrdiniPane.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        MainPanel = new JScrollPane();
        StoricoOrdiniPane.add(MainPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        tabellaOrdini = new JTable();
        MainPanel.setViewportView(tabellaOrdini);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return StoricoOrdiniPane;
    }

}
