package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import controller.ControllerCliente;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class FrameCreaOrdine extends JFrame {
    private JPanel pannelloPrincipale;
    private JPanel pannelloForm;
    private JPanel pannelloBottoni;
    private JButton xButton;
    private JTextField indirizzoSpedizione;
    private JLabel LabelIndirizzo;
    private JLabel LabelNumeroCarta;
    private JTextField numCartaTextField;
    private JLabel LabelCCV;
    private JTextField CCVTextField;
    private JLabel LabelMese;
    private JTextField meseTextField;
    private JLabel LabelAnno;
    private JTextField annoTextField;
    private JButton bottoneConferma;

    private String emailUtente;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pannelloPrincipale = new JPanel();
        pannelloPrincipale.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        pannelloForm = new JPanel();
        pannelloForm.setLayout(new GridLayoutManager(10, 1, new Insets(0, 0, 0, 0), -1, -1));
        pannelloPrincipale.add(pannelloForm, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        LabelIndirizzo = new JLabel();
        LabelIndirizzo.setText("IndirizzoSpedizione: ");
        pannelloForm.add(LabelIndirizzo, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        indirizzoSpedizione = new JTextField();
        pannelloForm.add(indirizzoSpedizione, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        LabelNumeroCarta = new JLabel();
        LabelNumeroCarta.setText("Numero Carta:");
        pannelloForm.add(LabelNumeroCarta, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        numCartaTextField = new JTextField();
        pannelloForm.add(numCartaTextField, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        LabelCCV = new JLabel();
        LabelCCV.setText("CCV:");
        pannelloForm.add(LabelCCV, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        CCVTextField = new JTextField();
        pannelloForm.add(CCVTextField, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        LabelMese = new JLabel();
        LabelMese.setText("Mese di scadenza:");
        pannelloForm.add(LabelMese, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        meseTextField = new JTextField();
        pannelloForm.add(meseTextField, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        LabelAnno = new JLabel();
        LabelAnno.setText("Anno di scadenza:");
        pannelloForm.add(LabelAnno, new GridConstraints(8, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        annoTextField = new JTextField();
        pannelloForm.add(annoTextField, new GridConstraints(9, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        pannelloBottoni = new JPanel();
        pannelloBottoni.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        pannelloPrincipale.add(pannelloBottoni, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        bottoneConferma = new JButton();
        bottoneConferma.setText("Conferma Ordine");
        pannelloBottoni.add(bottoneConferma, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        xButton = new JButton();
        xButton.setText("Esci");
        pannelloBottoni.add(xButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pannelloPrincipale;
    }

    public FrameCreaOrdine(String emailUtente) {
        this.emailUtente = emailUtente;

        setTitle("Creazione ordine");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Consigliato DISPOSE per chiudere solo questa finestra
        setLocationRelativeTo(null);

        setContentPane(pannelloPrincipale);

        impostaEventi();

        this.setVisible(true);
    }

    private void impostaEventi() {
        // Evento per il bottone Chiudi
        xButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Chiude la finestra e termina l'applicazione in modo sicuro
                dispose();
                System.exit(0);
            }
        });

        // Evento per il bottone Conferma
        bottoneConferma.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                elaboraDati();
            }
        });
    }

    private void elaboraDati() {
        ControllerCliente controllerCliente = new ControllerCliente(emailUtente);

        try {
            int ccv = Integer.parseInt(CCVTextField.getText());
            int mese = Integer.parseInt(meseTextField.getText());
            int anno = Integer.parseInt(annoTextField.getText());
            boolean check = controllerCliente.creaOrdine(indirizzoSpedizione.getText(), numCartaTextField.getText(), ccv, mese, anno);

            if (check) {
                JOptionPane.showMessageDialog(null, "Ordine creato con successo!");
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Errore durante la creazione dell'ordine.", "Ordine vuoto o pagamento non andato a buon fine",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            // Se l'utente inserisce lettere nei campi degli interi, catturiamo l'errore
            JOptionPane.showMessageDialog(this,
                    "Assicurati di inserire solo numeri validi nei campi 'Intero'.",
                    "Errore di Formato",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

/* check funzionamento
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new FrameCreaOrdine("r.giove@gmail.com"));
    }

 */
}
