package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import controller.ControllerAccesso;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

//fare semrpe check per credenziali amministratore al login

public class FrameAccesso {
    private JTextField textFieldEmail;
    private JPasswordField passwordField;
    private JButton accediButton;
    private JPanel accessoPane;
    private JLabel labelEsito;
    private JFrame frameMain;
    private JFrame MainframeCliente;
    private JFrame MainframeAmministratore;
    private JPanel MainPanel;

    public FrameAccesso(JFrame frameMain) {
        this();
        this.frameMain = frameMain;
    }


    public FrameAccesso() {
        accediButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //riempimento dati da interfaccia
                String email = textFieldEmail.getText();
                String password = passwordField.getText();
                //per il check del login
                String emailUtente = email;
                int esito = -1;  //metto come condizione iniziale quella di errore
                if (email.length() <= 40 && password.length() <= 40 && password.length() >= 8 && email.contains("@")) {
                    esito = ControllerAccesso.checkTipoUtente(email, password);  //delego la logica di controllo al controller per capire se le credenziali appartengono a un amministratore o a un cliente
                    if (esito == ControllerAccesso.UTENTE_AMM) {
                        //chiamata alla frame di admin
                        labelEsito.setText("Amministratore");
                        if (MainframeAmministratore == null || !MainframeAmministratore.isDisplayable()) {
                            new MainframeAmministratore(emailUtente);
                        } else {
                            MainframeAmministratore.toFront();
                            MainframeAmministratore.requestFocus();
                        }
                        if (frameMain != null) {
                            frameMain.dispose();
                        }
                        Window finestraAttuale = SwingUtilities.getWindowAncestor(accessoPane); //prende il riferimento alla finestra attuale per fare dispose
                        if (finestraAttuale != null) {
                            finestraAttuale.dispose();
                        }
                    } else if (esito == ControllerAccesso.UTENTE_CLIE) {
                        //chiamata alla frame di cliente
                        labelEsito.setText("Cliente");
                        if (MainframeCliente == null || !MainframeCliente.isDisplayable()) {
                            new MainframeCliente(emailUtente);
                        } else {
                            MainframeCliente.toFront();
                            MainframeCliente.requestFocus();
                        }
                        if (frameMain != null) {
                            frameMain.dispose();
                        }
                        Window finestraAttuale = SwingUtilities.getWindowAncestor(accessoPane);
                        if (finestraAttuale != null) {
                            finestraAttuale.dispose();
                        }

                    } else
                        //chiamata a frame di errore?
                        labelEsito.setText("Utente non trovato, riprova.");
                } else
                    labelEsito.setText("Errore dimensione campi.");
            }
        });
    }

    public JFrame apriFormAcc() {
        JFrame frame = new JFrame("Accesso");
        frame.setContentPane(accessoPane);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setSize(400, 300);
        frame.setResizable(false);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        return frame;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        accessoPane = new JPanel();
        accessoPane.setLayout(new GridLayoutManager(7, 4, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Accedi con le tue credenziali:");
        accessoPane.add(label1, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        textFieldEmail = new JTextField();
        textFieldEmail.setText("");
        accessoPane.add(textFieldEmail, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Email");
        accessoPane.add(label2, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Password");
        accessoPane.add(label3, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        passwordField = new JPasswordField();
        accessoPane.add(passwordField, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final Spacer spacer1 = new Spacer();
        accessoPane.add(spacer1, new GridConstraints(2, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        accessoPane.add(spacer2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        accessoPane.add(spacer3, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        accessoPane.add(spacer4, new GridConstraints(5, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        accediButton = new JButton();
        accediButton.setText("Accedi");
        accessoPane.add(accediButton, new GridConstraints(4, 1, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        labelEsito = new JLabel();
        labelEsito.setText("In attesa dell'esito...");
        accessoPane.add(labelEsito, new GridConstraints(6, 1, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Esito:");
        accessoPane.add(label4, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return accessoPane;
    }

}
