package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import controller.ControllerAmministratore;
import controller.ControllerCliente;
import entity.Ordine;
import entity.Stato;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

//TODO: testare la funzionalità

public class FrameDettaglioOrdine extends JFrame {
    //Variabili per il GUI Designer
    private JPanel PanelOrdine;
    private JLabel lblId;
    private JLabel lblTotale;
    private JLabel lblOggettiAcquistati;
    private JLabel lblDataConferma;
    private JLabel lblIndirizzoSpedizione;
    private JLabel lblStato;
    private JButton btnChiudi;
    private JButton btnAnnullaOrdine;

    //Variabili per la logica BCED
    private ControllerCliente controllerCliente;
    private ControllerAmministratore controllerAmministratore;

    private boolean isAmministratore; //sarà il nostro modo per riconoscere
    // se questa frame è stata aperta da FrameCliente o da FrameAmministratore
    private Ordine ordineSelezionato;

    //costruttore della boundary
    public FrameDettaglioOrdine(ControllerCliente controller, Ordine ordine) {
        this.controllerCliente = controller;
        this.isAmministratore = false;
        this.ordineSelezionato = ordine;

        apriFrame();
    }

    public FrameDettaglioOrdine(ControllerAmministratore controller, Ordine ordine) {
        this.controllerAmministratore = controller;
        this.isAmministratore = true;
        this.ordineSelezionato = ordine;

        apriFrame();
    }

    private void apriFrame() {
        setTitle("Ecco l'ordine selezionato:");
        setContentPane(PanelOrdine);
        setSize(700, 350);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        fillTabella();
        addListenerBottoni();
    }

    private void fillTabella() {
        //metodo di Test
        System.out.println("PROVA");
    }

    private void addListenerBottoni() {
        btnChiudi.addActionListener(e -> dispose());

        btnAnnullaOrdine.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int conferma = JOptionPane.showConfirmDialog(
                        PanelOrdine,
                        "Vuoi annullare l'ordine?",
                        "Conferma",
                        JOptionPane.YES_NO_OPTION);

                if (conferma == JOptionPane.YES_OPTION) {
                    boolean successo = false;

                    // CONTROLLO DEL RUOLO: Scegliamo a quale controller chiedere l'annullamento
                    if (isAmministratore) {
                        successo = controllerAmministratore.richiediAnnullamentoOrdine(ordineSelezionato);
                    } else {
                        successo = controllerCliente.richiediAnnullamentoOrdine(ordineSelezionato);
                    }

                    if (successo) {
                        lblStato.setText(Stato.ANNULLATO.toString());
                        btnAnnullaOrdine.setEnabled(false);
                        JOptionPane.showMessageDialog(PanelOrdine, "Ordine annullato.");
                    } else {
                        JOptionPane.showMessageDialog(PanelOrdine, "Errore durante l'annullamento.", "Errore", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        PanelOrdine = new JPanel();
        PanelOrdine.setLayout(new GridLayoutManager(7, 2, new Insets(2, 2, 2, 2), -1, -1));
        lblDataConferma = new JLabel();
        lblDataConferma.setText("Label");
        PanelOrdine.add(lblDataConferma, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblIndirizzoSpedizione = new JLabel();
        lblIndirizzoSpedizione.setText("Label");
        PanelOrdine.add(lblIndirizzoSpedizione, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblId = new JLabel();
        lblId.setText("Label");
        PanelOrdine.add(lblId, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblTotale = new JLabel();
        lblTotale.setText("Label");
        PanelOrdine.add(lblTotale, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Totale (€):");
        PanelOrdine.add(label1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Data Conferma Ordine:");
        PanelOrdine.add(label2, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Indirizzo Spedizione");
        PanelOrdine.add(label3, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("ID Ordine:");
        PanelOrdine.add(label4, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("Oggetti Acquistati:");
        PanelOrdine.add(label5, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblOggettiAcquistati = new JLabel();
        lblOggettiAcquistati.setText("Label");
        PanelOrdine.add(lblOggettiAcquistati, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label6 = new JLabel();
        label6.setText("Stato Ordine");
        PanelOrdine.add(label6, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblStato = new JLabel();
        lblStato.setText("Label");
        PanelOrdine.add(lblStato, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnChiudi = new JButton();
        btnChiudi.setText("Chiudi");
        PanelOrdine.add(btnChiudi, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnAnnullaOrdine = new JButton();
        btnAnnullaOrdine.setText("Annulla Ordine");
        PanelOrdine.add(btnAnnullaOrdine, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return PanelOrdine;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
