package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import controller.ControllerCliente;

import javax.swing.*;
import java.awt.*;
import java.util.List;


public class FrameCarrello extends JFrame {

    private JPanel contentPanel;
    private JScrollPane scrollPane;
    private JPanel panelCarrello;

    public FrameCarrello() {
        //design
        setTitle("Il tuo carrello");
        setContentPane(contentPanel);
        setSize(800, 600);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);

        //Scorrimento
        panelCarrello.setLayout(new BoxLayout(panelCarrello, BoxLayout.Y_AXIS));

        //Riempimento
        fillCarrello();
        setVisible(true);

    }

    /*//Per testare se la schermata va
    public static void main(String[] args) {
        new FrameCarrello();
    }
    */

    private void fillCarrello() {
        panelCarrello.removeAll();

        List<String[]> prodotti = ControllerCliente.getCarrelloBreve();

        if (prodotti == null || prodotti.isEmpty()) {
            panelCarrello.add(new JLabel("Carrello vuoto"));
        } else {
            for (String[] p : prodotti) {
                JPanel panelProdotto = new JPanel(new BorderLayout(15, 10));
                panelProdotto.setBorder(BorderFactory.createCompoundBorder(
                        BorderFactory.createEmptyBorder(10, 10, 10, 10),
                        BorderFactory.createEtchedBorder()
                ));
                panelProdotto.setMaximumSize(new Dimension(Integer.MAX_VALUE, 100));

                //Spacchetto la stringa
                String nome = p[0];
                String descrizione = p[1];
                String prezzo = p[2];
                String categoria = p[3];
                String quantita = p[4];

                String testoHtml = "<html><h3 style='margin:0;'>" + nome + " <span style='font-size:10px; color:gray'>(" + categoria + ")</span></h3>" +
                        "<p style='margin:0;'><i>" + descrizione + "</i></p>" +
                        "<p style='margin:0; margin-top:5px;'>Prezzo: <b>" + prezzo + " €</b> | Quantità nel carrello: <b>" + quantita + "</b></p></html>";

                JLabel lblInfo = new JLabel(testoHtml);
                JButton btnRimuovi = new JButton("Rimuovi dal carrello");
                btnRimuovi.setBackground(Color.RED);
                btnRimuovi.setForeground(Color.WHITE);

                //Action per la rimozione (btnRimuovi)
                btnRimuovi.addActionListener(e -> {
                    int dialogResult = JOptionPane.showConfirmDialog(this, "Sei sicuro di voler rimuovere " + nome + "?", "Conferma", JOptionPane.YES_NO_OPTION);
                    if (dialogResult == JOptionPane.YES_OPTION) {
                        boolean rimosso = ControllerCliente.rimuoviProdottoDalCarrello(nome);
                        if (rimosso) {
                            JOptionPane.showMessageDialog(this, "Prodotto rimosso con successo.");
                            fillCarrello(); // Ricarica la grafica per far sparire il pannello
                        } else {
                            JOptionPane.showMessageDialog(this, "Errore nella rimozione.", "Errore", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                });

                panelProdotto.add(lblInfo, BorderLayout.CENTER);
                panelProdotto.add(btnRimuovi, BorderLayout.EAST);
                panelCarrello.add(panelProdotto);
                panelCarrello.add(Box.createRigidArea(new Dimension(0, 10)));
            }
        }
        panelCarrello.revalidate();
        panelCarrello.repaint();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Prodotti presenti nel carrello");
        contentPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        contentPanel.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        scrollPane = new JScrollPane();
        contentPanel.add(scrollPane, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        panelCarrello = new JPanel();
        panelCarrello.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        scrollPane.setViewportView(panelCarrello);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }
}
