package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MainframeAccesso {
    private JPanel MainPanel;
    private JLabel Welcome;
    private JButton RegistrazioneButton;
    private JButton AccessoButton;

    private JFrame FrameRegistrazione;
    private JFrame FrameAccesso;

    public MainframeAccesso() {
        RegistrazioneButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (FrameRegistrazione == null || !FrameRegistrazione.isDisplayable()) {
                    FrameRegistrazione formreg = new FrameRegistrazione();
                    FrameRegistrazione = formreg.apriFormReg();
                    FrameRegistrazione.setLocationRelativeTo(null);
                    FrameRegistrazione.setVisible(true);
                } else {
                    FrameRegistrazione.toFront();
                    FrameRegistrazione.requestFocus();
                }
            }
        });

        AccessoButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (FrameAccesso == null || !FrameAccesso.isDisplayable()) {
                    FrameAccesso formacc = new FrameAccesso();
                    FrameAccesso = formacc.apriFormAcc();
                    FrameAccesso.setLocationRelativeTo(null);
                    FrameAccesso.setVisible(true);
                } else {
                    FrameAccesso.toFront();
                    FrameAccesso.requestFocus();
                }
            }
        });
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("Homepage");
        MainframeAccesso mainframe = new MainframeAccesso();
        frame.setContentPane(mainframe.MainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(500, 400);
        frame.setResizable(false);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPanel = new JPanel();
        MainPanel.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1, true, false));
        Welcome = new JLabel();
        Welcome.setText("Benvenuto nella Homepage");
        MainPanel.add(Welcome, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(173, 263), null, 0, false));
        RegistrazioneButton = new JButton();
        RegistrazioneButton.setText("Registrati");
        MainPanel.add(RegistrazioneButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        AccessoButton = new JButton();
        AccessoButton.setText("Accedi");
        MainPanel.add(AccessoButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        MainPanel.add(spacer1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(265, 14), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }

}
